"""
pdf_tab.py — PDF Preview & Download tab (PyQt6)

Displays the exact PDF that build_pdf_report() (pdf_engine.py, unmodified)
produces, using QWebEngineView's built-in Chromium PDF viewer — so what you
see IS the PDF, not an approximation of it. "Refresh Preview" re-runs the
assembly callback provided by MainWindow (which gathers Initial/Results/
Test Check/Measurable data + saved plots from the other tabs). "Download"
just writes the already-generated bytes to a location you choose — no
re-generation, so what you download always matches what you previewed.
"""

import tempfile
from pathlib import Path

from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QFileDialog, QMessageBox
)
from PyQt6.QtCore import QUrl
from PyQt6.QtWebEngineWidgets import QWebEngineView


class PdfTab(QWidget):
    def __init__(self, generate_callback):
        """generate_callback: () -> (pdf_bytes, suggested_filename) or (None, None) on failure."""
        super().__init__()
        self.generate_callback = generate_callback
        self.pdf_bytes = None
        self.suggested_filename = "report.pdf"
        self._temp_pdf_path = None

        root = QVBoxLayout(self)

        top_row = QHBoxLayout()
        refresh_btn = QPushButton("🔄 Refresh Preview")
        refresh_btn.clicked.connect(self.refresh_preview)
        top_row.addWidget(refresh_btn)

        self.download_btn = QPushButton("⬇️  Download PDF Report")
        self.download_btn.clicked.connect(self.download)
        self.download_btn.setEnabled(False)
        top_row.addWidget(self.download_btn)
        top_row.addStretch()
        root.addLayout(top_row)

        self.status_label = QLabel(
            "Click \"Refresh Preview\" to generate a report from the current run."
        )
        self.status_label.setStyleSheet("color:#6b7280; font-size:11px;")
        root.addWidget(self.status_label)

        self.preview = QWebEngineView()
        self.preview.setMinimumHeight(600)
        root.addWidget(self.preview, stretch=1)
        self._show_placeholder()

    def _show_placeholder(self):
        self.preview.setHtml(
            "<html><body style='background:#0d0f14; color:#6b7280; "
            "font-family:sans-serif; display:flex; align-items:center; "
            "justify-content:center; height:100vh; margin:0;'>"
            "No report generated yet.</body></html>"
        )

    def refresh_preview(self):
        self.status_label.setText("Building PDF report…")
        try:
            pdf_bytes, suggested_filename = self.generate_callback()
        except Exception as e:
            QMessageBox.critical(self, "PDF generation failed", str(e))
            self.status_label.setText("⚠️ PDF generation failed — see error dialog.")
            return

        if pdf_bytes is None:
            self.status_label.setText("⚠️ No run loaded — import or open a log first.")
            return

        self.pdf_bytes = pdf_bytes
        self.suggested_filename = suggested_filename or "report.pdf"
        self.download_btn.setEnabled(True)

        # Write to a temp file and load it — QWebEngineView renders PDFs
        # natively via Chromium's built-in viewer when given a file:// URL.
        tmp_dir = Path(tempfile.gettempdir())
        self._temp_pdf_path = tmp_dir / "thrust_dashboard_preview.pdf"
        self._temp_pdf_path.write_bytes(pdf_bytes)
        self.preview.setUrl(QUrl.fromLocalFile(str(self._temp_pdf_path)))

        self.status_label.setText(
            f"✅ Report ready — {len(pdf_bytes) / 1024:.0f} KB. "
            f"This is exactly what will be downloaded."
        )

    def download(self):
        if not self.pdf_bytes:
            return
        path_str, _ = QFileDialog.getSaveFileName(
            self, "Save PDF report", self.suggested_filename, "PDF files (*.pdf)"
        )
        if not path_str:
            return
        Path(path_str).write_bytes(self.pdf_bytes)
        self.status_label.setText(f"✅ Saved to {path_str}")
