"""
pdf_tab.py — PDF Preview & Download tab (PyQt6)

Displays the exact PDF that build_pdf_report() (pdf_engine.py, unmodified)
produces. "Refresh Preview" re-runs the assembly callback provided by
MainWindow (which gathers Initial/Results/Test Check/Measurable data +
saved plots from the other tabs, filtered by the checkboxes below).
"Download" just writes the already-generated bytes to a location you
choose — no re-generation, so what you download always matches what you
previewed.

Preview implementation note: this renders each PDF page to a PNG (via
PyMuPDF) and displays those images in the QWebEngineView, rather than
handing Chromium a file:// URL to the PDF directly (even wrapped in an
<embed> tag). Both of those were tried and both failed silently —
Chromium either intercepts a direct local-PDF navigation as a download
and cancels the page load, or the embedded PDF plugin fails to load the
local file from HTML loaded via setHtml() (shows as a blank/white pane
either way, no error). Rendering to plain images sidesteps all of that.
"""

import base64
from pathlib import Path

import pymupdf
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QCheckBox,
    QFileDialog, QMessageBox, QGroupBox
)
from PyQt6.QtWebEngineWidgets import QWebEngineView

# Section keys must match what pdf_engine.build_pdf_report()'s `sections`
# dict looks for.
_SECTIONS = [
    ("initial_params",    "Initial Parameters (incl. Observations)"),
    ("test_param_check",  "Test Parameter Check"),
    ("results",           "Results"),
    ("measurable_params", "Measurable Params (efficiency)"),
    ("charts",            "Test Charts (Saved Plots)"),
]


class PdfTab(QWidget):
    def __init__(self, generate_callback, docx_generate_callback=None):
        """generate_callback: (sections: dict) -> (pdf_bytes, suggested_filename)
        or (None, None) on failure.
        docx_generate_callback: same shape, for the editable Word version —
        built from identical underlying data (see MainWindow._assemble_report_data),
        so PDF and DOCX always agree on content."""
        super().__init__()
        self.generate_callback = generate_callback
        self.docx_generate_callback = docx_generate_callback
        self.pdf_bytes = None
        self.docx_bytes = None
        self.suggested_filename = "report.pdf"
        self.suggested_docx_filename = "report.docx"

        root = QVBoxLayout(self)

        # ── Section checklist — single place that decides what goes in
        # the PDF, instead of a toggle scattered across each source tab.
        sections_box = QGroupBox("Include in Report")
        sections_row = QHBoxLayout(sections_box)
        self.section_checks = {}
        for key, label in _SECTIONS:
            cb = QCheckBox(label)
            cb.setChecked(True)
            self.section_checks[key] = cb
            sections_row.addWidget(cb)
        sections_row.addStretch()
        root.addWidget(sections_box)

        top_row = QHBoxLayout()
        refresh_btn = QPushButton("🔄 Refresh Preview")
        refresh_btn.clicked.connect(self.refresh_preview)
        top_row.addWidget(refresh_btn)

        self.download_btn = QPushButton("⬇️  Download PDF Report")
        self.download_btn.clicked.connect(self.download)
        self.download_btn.setEnabled(False)
        top_row.addWidget(self.download_btn)

        self.download_docx_btn = QPushButton("⬇️  Download as Word (.docx)")
        self.download_docx_btn.clicked.connect(self.download_docx)
        self.download_docx_btn.setEnabled(False)
        top_row.addWidget(self.download_docx_btn)
        top_row.addStretch()
        root.addLayout(top_row)

        self.status_label = QLabel(
            "Click \"Refresh Preview\" to generate a report from the current run."
        )
        self.status_label.setStyleSheet("color:#6b7280; font-size:11px;")
        root.addWidget(self.status_label)

        self.preview = QWebEngineView()
        self.preview.setMinimumHeight(600)
        root.addWidget(self.preview, stretch=1)
        self._show_placeholder()

    def get_sections(self) -> dict:
        """{'initial_params': True, 'test_param_check': False, ...}"""
        return {key: cb.isChecked() for key, cb in self.section_checks.items()}

    def _show_placeholder(self):
        self.preview.setHtml(
            "<html><body style='background:#0d0f14; color:#6b7280; "
            "font-family:sans-serif; display:flex; align-items:center; "
            "justify-content:center; height:100vh; margin:0;'>"
            "No report generated yet.</body></html>"
        )

    def refresh_preview(self):
        self.status_label.setText("Building PDF report…")
        try:
            pdf_bytes, suggested_filename = self.generate_callback(self.get_sections())
        except Exception as e:
            QMessageBox.critical(self, "PDF generation failed", str(e))
            self.status_label.setText("⚠️ PDF generation failed — see error dialog.")
            return

        if pdf_bytes is None:
            self.status_label.setText("⚠️ No run loaded — import or open a log first.")
            return

        self.pdf_bytes = pdf_bytes
        self.suggested_filename = suggested_filename or "report.pdf"
        self.download_btn.setEnabled(True)

        if self.docx_generate_callback:
            try:
                docx_bytes, docx_filename = self.docx_generate_callback(self.get_sections())
                self.docx_bytes = docx_bytes
                self.suggested_docx_filename = docx_filename or "report.docx"
                self.download_docx_btn.setEnabled(docx_bytes is not None)
            except Exception as e:
                self.docx_bytes = None
                self.download_docx_btn.setEnabled(False)
                # Don't block the PDF flow over a DOCX failure — just surface it.
                QMessageBox.warning(self, "Word document generation failed", str(e))

        try:
            self._render_preview(pdf_bytes)
        except Exception as e:
            QMessageBox.critical(self, "Preview rendering failed", str(e))
            self.status_label.setText(
                f"⚠️ Report generated ({len(pdf_bytes) / 1024:.0f} KB) but the "
                f"preview couldn't be rendered — you can still download it."
            )
            return

        self.status_label.setText(
            f"✅ Report ready — {len(pdf_bytes) / 1024:.0f} KB. "
            f"This is exactly what will be downloaded."
        )

    def _render_preview(self, pdf_bytes: bytes):
        """Rasterize each page to a PNG and lay them out as stacked <img>
        tags — see module docstring for why this is used instead of
        pointing the view at the PDF file directly."""
        doc = pymupdf.open(stream=pdf_bytes, filetype="pdf")
        zoom = 150 / 72  # ~150 DPI
        matrix = pymupdf.Matrix(zoom, zoom)

        img_tags = []
        for page in doc:
            pix = page.get_pixmap(matrix=matrix)
            png_bytes = pix.tobytes("png")
            b64 = base64.b64encode(png_bytes).decode("ascii")
            img_tags.append(
                f"<img src='data:image/png;base64,{b64}' "
                "style='display:block; width:100%; max-width:900px; "
                "margin:0 auto 12px auto; box-shadow:0 2px 10px rgba(0,0,0,0.5);'>"
            )
        doc.close()

        html = f"""
        <html><head><style>
            html, body {{ margin:0; padding:16px 0; background:#3a3d46; box-sizing:border-box; }}
        </style></head>
        <body>{''.join(img_tags)}</body>
        </html>
        """
        self.preview.setHtml(html)

    def download(self):
        if not self.pdf_bytes:
            return
        path_str, _ = QFileDialog.getSaveFileName(
            self, "Save PDF report", self.suggested_filename, "PDF files (*.pdf)"
        )
        if not path_str:
            return
        Path(path_str).write_bytes(self.pdf_bytes)
        self.status_label.setText(f"✅ Saved to {path_str}")

    def download_docx(self):
        if not self.docx_bytes:
            return
        path_str, _ = QFileDialog.getSaveFileName(
            self, "Save Word report", self.suggested_docx_filename,
            "Word documents (*.docx)"
        )
        if not path_str:
            return
        Path(path_str).write_bytes(self.docx_bytes)
        self.status_label.setText(f"✅ Saved to {path_str}")
